language: java
os: linux
dist: xenial

cache:
  directories:
    - "$HOME/.m2"

addons:
  sonarcloud:
    organization: "selcukes"
    token: $SONAR_TOKEN

jobs:
  include:
    # 1.1 Sonar check JDK 8
    - stage: test
      jdk: openjdk8
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=selcukes_webdriver-binaries

    # 1.2 Check JDK 10,11
    - stage: test
      jdk: openjdk10
      script: mvn clean verify
      after_success:
        - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
    - jdk: openjdk11
      script: mvn -q verify
