language: java
sudo: false

addons:
  sonarcloud:
    organization: "selcukes"
    token:
      secure: "0d8b8dded5d5f28f9a714435e888724105084230"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
  # 1.1 Semver check
  - stage: test
    jdk: openjdk8
    script: mvn verify -Pcheck-semantic-version -DskipTests=true
    env: CHECK_SEMANTIC_VERSION=true

  # 1.2 Check JDK 8,10,ea
  - stage: test
    jdk: openjdk8
    script: mvn clean verify
    after_success:
      - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
  - jdk: openjdk10
    script: mvn -q verify


branches:
  only:
  - master
