language: java
sudo: false

cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
  # 1.1 Semver check
  - stage: test
    jdk: openjdk8
    script: mvn verify -Pcheck-semantic-version -DskipTests=true
    env: CHECK_SEMANTIC_VERSION=true

  # 1.2 Check JDK 8,10,ea
  - stage: test
    jdk: openjdk8
    script: mvn clean verify
    after_success:
      - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
  - jdk: openjdk10
    script: mvn -q verify


branches:
  only:
  - master
