language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:

    # 1.1 Sonar check JDK 8
    - stage: test
      jdk: openjdk8
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=selcukes_selcukes-reports

    # 1.2 Check JDK 10,11
    - stage: test
      jdk: openjdk10
      script: mvn clean verify
      after_success:
        - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
    - jdk: openjdk11
      script: mvn -q verify

addons:
  sonarcloud:
    organization: "selcukes"
    token:
      secure: $SONAR_TOKEN

branches:
only:
  - master
