language: java
os: linux
dist: xenial

cache:
  directories:
    - "$HOME/.m2"

install: true

addons:
  chrome: stable
  firefox: latest
  sonarcloud:
    organization: "selcukes"
    token: $SONAR_TOKEN

jobs:
  include:
    # 1.1 Sonar check JDK 11
    - stage: test
      jdk: openjdk11
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=selcukes_selcukes-java

